/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View.BasicPanels;

/**
 *
 * @author enric
 */
public class panelStars extends javax.swing.JPanel {
    boolean rated = false;
    int rating;
    /**
     * Creates new form panelStars
     */
    public panelStars() {
        initComponents();
    }
    
    public void setOffStars(){
        ratingStar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/offStar.jpg")));
        ratingStar2.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/offStar.jpg")));
        ratingStar3.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/offStar.jpg")));
        ratingStar4.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/offStar.jpg")));
        ratingStar5.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/offStar.jpg")));
    }
    
    public void checkRate(){
        rated = false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingStar1 = new totseries_it1b.View.BasicPanels.RatingStar();
        ratingStar2 = new totseries_it1b.View.BasicPanels.RatingStar();
        ratingStar3 = new totseries_it1b.View.BasicPanels.RatingStar();
        ratingStar4 = new totseries_it1b.View.BasicPanels.RatingStar();
        ratingStar5 = new totseries_it1b.View.BasicPanels.RatingStar();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ratingStar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar1MouseEntered(evt);
            }
        });
        add(ratingStar1);

        ratingStar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar2MouseEntered(evt);
            }
        });
        add(ratingStar2);

        ratingStar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar3MouseEntered(evt);
            }
        });
        add(ratingStar3);

        ratingStar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar4MouseEntered(evt);
            }
        });
        add(ratingStar4);

        ratingStar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar5MouseEntered(evt);
            }
        });
        add(ratingStar5);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if(!rated){
            setOffStars();
        }
    }//GEN-LAST:event_formMouseExited

    private void ratingStar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar1MouseClicked
        rated = true;
        rating = 1;
    }//GEN-LAST:event_ratingStar1MouseClicked

    private void ratingStar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar2MouseClicked
        rated = true;
        rating = 2;
    }//GEN-LAST:event_ratingStar2MouseClicked

    private void ratingStar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar3MouseClicked
        rated = true;
        rating = 3;
    }//GEN-LAST:event_ratingStar3MouseClicked

    private void ratingStar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar4MouseClicked
        rated = true;
        rating = 4;
    }//GEN-LAST:event_ratingStar4MouseClicked

    private void ratingStar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar5MouseClicked
        rated = true;
        rating = 5;
    }//GEN-LAST:event_ratingStar5MouseClicked

    private void ratingStar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar1MouseEntered
        ratingStar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg"))); 
    }//GEN-LAST:event_ratingStar1MouseEntered

    private void ratingStar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar2MouseEntered
        if(!rated){
            ratingStar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar2.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
        }
    }//GEN-LAST:event_ratingStar2MouseEntered

    private void ratingStar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar3MouseEntered
        if(!rated){
            ratingStar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar2.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar3.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
        }
    }//GEN-LAST:event_ratingStar3MouseEntered

    private void ratingStar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar4MouseEntered
        if(!rated){
            ratingStar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar2.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar3.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar4.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
        }
    }//GEN-LAST:event_ratingStar4MouseEntered

    private void ratingStar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar5MouseEntered
        if(!rated){  
            ratingStar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar2.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar3.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar4.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
            ratingStar5.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/onStar.jpg")));
        }
    }//GEN-LAST:event_ratingStar5MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar1;
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar2;
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar3;
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar4;
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar5;
    // End of variables declaration//GEN-END:variables
}
