/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View.BasicPanels;

import javax.swing.JOptionPane;
import totseries_it1b.Controller.TSController;

/**
 *
 * @author enric
 */
public class panelStars extends javax.swing.JPanel {

    private boolean rated = false;
    private int rating;
    private int viewId;
    private String serieId;
    private int numSeason;
    private int numEp;

    /**
     * Creates new form panelStars
     */
    public panelStars() {
        initComponents();
    }

    public void load(String serieId, int numSeason, int numEp) {
        this.serieId = serieId;
        this.numSeason = numSeason;
        this.numEp = numEp;

        TSController ctrl = TSController.getInstance();
        if (ctrl.userIsClient()) {
            int rate = ctrl.getClientRateOfEpisode(serieId, numSeason, numEp);
            if (rate != -1) {
                setPreviouslyRated(rate);
                this.setVisible(true);
            }
        }
    }

    public void reset() {
        setVisible(false);
        setOffStars();
        checkRate();
    }

    public void setOffStars() {
        ratingStar1.setOff();
        ratingStar2.setOff();
        ratingStar3.setOff();
        ratingStar4.setOff();
        ratingStar5.setOff();
    }

    public void checkRate() {
        rated = false;
    }

    public void setViewId(int id) {
        viewId = id;
    }

    private void rate() {
        TSController ctrl = TSController.getInstance();
        if (ctrl.userIsClient()) {
            // Tenim viewId
            ctrl.rateEpisode(viewId, rating);
        } else if (ctrl.userIsAdmin()) {
            // Preguntem quants cops vol valorar aquest episodi.
            String count = JOptionPane.showInputDialog("How many times do you want to rate this episode with a " + rating + "/5?");
            int intCount = Integer.parseInt(count);
            ctrl.rateEpisodeByAdmin(serieId, numSeason, numEp, rating, intCount);
            reset();
            setVisible(true);
        }
        JOptionPane.showMessageDialog(null, "Thanks for rating this episode!");
    }

    private void setPreviouslyRated(int rating) {
        switch (rating) {
            case 5:
                ratingStar5.setOn();
            case 4:
                ratingStar4.setOn();
            case 3:
                ratingStar3.setOn();
            case 2:
                ratingStar2.setOn();
            case 1:
                ratingStar1.setOn();
        }
        rated = true;
        this.rating = rating;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratingStar1 = new totseries_it1b.View.BasicPanels.RatingStar();
        ratingStar2 = new totseries_it1b.View.BasicPanels.RatingStar();
        ratingStar3 = new totseries_it1b.View.BasicPanels.RatingStar();
        ratingStar4 = new totseries_it1b.View.BasicPanels.RatingStar();
        ratingStar5 = new totseries_it1b.View.BasicPanels.RatingStar();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        ratingStar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar1MouseEntered(evt);
            }
        });
        add(ratingStar1);

        ratingStar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar2MouseEntered(evt);
            }
        });
        add(ratingStar2);

        ratingStar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar3MouseEntered(evt);
            }
        });
        add(ratingStar3);

        ratingStar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar4MouseEntered(evt);
            }
        });
        add(ratingStar4);

        ratingStar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ratingStar5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ratingStar5MouseEntered(evt);
            }
        });
        add(ratingStar5);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        if (!rated) {
            setOffStars();
        }
    }//GEN-LAST:event_formMouseExited

    private void ratingStar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar1MouseClicked
        if (!rated) {
            rated = true;
            rating = 1;
            rate();
        }
    }//GEN-LAST:event_ratingStar1MouseClicked

    private void ratingStar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar2MouseClicked
        if (!rated) {
            rated = true;
            rating = 2;
            rate();
        }
    }//GEN-LAST:event_ratingStar2MouseClicked

    private void ratingStar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar3MouseClicked
        if (!rated) {
            rated = true;
            rating = 3;
            rate();
        }
    }//GEN-LAST:event_ratingStar3MouseClicked

    private void ratingStar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar4MouseClicked
        if (!rated) {
            rated = true;
            rating = 4;
            rate();
        }
    }//GEN-LAST:event_ratingStar4MouseClicked

    private void ratingStar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar5MouseClicked
        if (!rated) {
            rated = true;
            rating = 5;
            rate();
        }
    }//GEN-LAST:event_ratingStar5MouseClicked

    private void ratingStar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar1MouseEntered
        ratingStar1.setOn();
    }//GEN-LAST:event_ratingStar1MouseEntered

    private void ratingStar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar2MouseEntered
        if (!rated) {
            ratingStar1.setOn();
            ratingStar2.setOn();
        }
    }//GEN-LAST:event_ratingStar2MouseEntered

    private void ratingStar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar3MouseEntered
        if (!rated) {
            ratingStar1.setOn();
            ratingStar2.setOn();
            ratingStar3.setOn();
        }
    }//GEN-LAST:event_ratingStar3MouseEntered

    private void ratingStar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar4MouseEntered
        if (!rated) {
            ratingStar1.setOn();
            ratingStar2.setOn();
            ratingStar3.setOn();
            ratingStar4.setOn();
        }
    }//GEN-LAST:event_ratingStar4MouseEntered

    private void ratingStar5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ratingStar5MouseEntered
        if (!rated) {
            ratingStar1.setOn();
            ratingStar2.setOn();
            ratingStar3.setOn();
            ratingStar4.setOn();
            ratingStar5.setOn();
        }
    }//GEN-LAST:event_ratingStar5MouseEntered

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar1;
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar2;
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar3;
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar4;
    private totseries_it1b.View.BasicPanels.RatingStar ratingStar5;
    // End of variables declaration//GEN-END:variables
}
