/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View.BasicPanels;

import java.awt.Color;

/**
 *
 * @author Enric Calvo & German Barquero
 */
public class ViewsPanel extends javax.swing.JPanel {

    private int num;

    /**
     * Creates new form ViewsPanel
     */
    public ViewsPanel(int num) {
        initComponents();
        viewsNum.setText(Integer.toString(num) + " views");
        setBackground(new Color(0, 0, 0, 170));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewsNum = new javax.swing.JLabel();

        viewsNum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        viewsNum.setForeground(new java.awt.Color(255, 255, 255));
        viewsNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewsNum.setText("UNDEFINED");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewsNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(viewsNum, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel viewsNum;
    // End of variables declaration//GEN-END:variables
}
