/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View.Rankings.MostViewed;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author Enric Calvo & German Barquero
 */
public class ByViewsRankingsPanel extends javax.swing.JPanel {

    private int mainCase = 0;

    /**
     * Creates new form ByViewsRankingsPanel
     */
    public ByViewsRankingsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new javax.swing.JPanel();
        seriesButton = new javax.swing.JPanel();
        seriesLabel = new javax.swing.JLabel();
        episodesButton = new javax.swing.JPanel();
        episodesLabel = new javax.swing.JLabel();
        seasonsButton = new javax.swing.JPanel();
        seasonsLabel = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        seriesByViewsRanking1 = new totseries_it1b.View.Rankings.MostViewed.SeriesByViewsRanking();
        seasonsByViewsRanking1 = new totseries_it1b.View.Rankings.MostViewed.SeasonsByViewsRanking();
        episodesByViewsRanking1 = new totseries_it1b.View.Rankings.MostViewed.EpisodesByViewsRanking();

        setBackground(new java.awt.Color(255, 255, 255));

        buttonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        seriesButton.setBackground(Color.GRAY);

        seriesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seriesLabel.setText("Series");
        seriesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seriesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seriesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seriesLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout seriesButtonLayout = new javax.swing.GroupLayout(seriesButton);
        seriesButton.setLayout(seriesButtonLayout);
        seriesButtonLayout.setHorizontalGroup(
            seriesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seriesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        seriesButtonLayout.setVerticalGroup(
            seriesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seriesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        episodesButton.setBackground(new java.awt.Color(255, 255, 255));

        episodesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        episodesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        episodesLabel.setText("Episodes");
        episodesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                episodesLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                episodesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                episodesLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout episodesButtonLayout = new javax.swing.GroupLayout(episodesButton);
        episodesButton.setLayout(episodesButtonLayout);
        episodesButtonLayout.setHorizontalGroup(
            episodesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, episodesButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(episodesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        episodesButtonLayout.setVerticalGroup(
            episodesButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(episodesLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        seasonsButton.setBackground(new java.awt.Color(255, 255, 255));

        seasonsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        seasonsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seasonsLabel.setText("Seasons");
        seasonsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seasonsLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                seasonsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                seasonsLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout seasonsButtonLayout = new javax.swing.GroupLayout(seasonsButton);
        seasonsButton.setLayout(seasonsButtonLayout);
        seasonsButtonLayout.setHorizontalGroup(
            seasonsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seasonsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        seasonsButtonLayout.setVerticalGroup(
            seasonsButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seasonsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seasonsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(episodesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(episodesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seriesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seasonsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(buttonsPanel);

        mainContainer.setBackground(new java.awt.Color(255, 255, 255));
        mainContainer.setLayout(new java.awt.CardLayout());
        mainContainer.add(seriesByViewsRanking1, "seriesCard");
        mainContainer.add(seasonsByViewsRanking1, "seasonsCard");
        mainContainer.add(episodesByViewsRanking1, "episodesCard");

        add(mainContainer);
    }// </editor-fold>//GEN-END:initComponents

    private void seriesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seriesLabelMouseClicked
        mainCase = 0;
        seriesButton.setBackground(Color.GRAY);
        seasonsButton.setBackground(Color.WHITE);
        episodesButton.setBackground(Color.WHITE);
        CardLayout card = (CardLayout) mainContainer.getLayout();
        card.show(mainContainer, "seriesCard");
    }//GEN-LAST:event_seriesLabelMouseClicked

    private void seriesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seriesLabelMouseEntered
        seriesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seriesButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_seriesLabelMouseEntered

    private void seriesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seriesLabelMouseExited
        if (mainCase != 0) {
            seriesButton.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_seriesLabelMouseExited

    private void episodesLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_episodesLabelMouseClicked
        mainCase = 2;
        seriesButton.setBackground(Color.WHITE);
        seasonsButton.setBackground(Color.WHITE);
        episodesButton.setBackground(Color.GRAY);
        CardLayout card = (CardLayout) mainContainer.getLayout();
        card.show(mainContainer, "episodesCard");
    }//GEN-LAST:event_episodesLabelMouseClicked

    private void episodesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_episodesLabelMouseEntered
        episodesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        episodesButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_episodesLabelMouseEntered

    private void episodesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_episodesLabelMouseExited
        if (mainCase != 2) {
            episodesButton.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_episodesLabelMouseExited

    private void seasonsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seasonsLabelMouseClicked
        mainCase = 1;
        seriesButton.setBackground(Color.WHITE);
        seasonsButton.setBackground(Color.GRAY);
        episodesButton.setBackground(Color.WHITE);
        CardLayout card = (CardLayout) mainContainer.getLayout();
        card.show(mainContainer, "seasonsCard");
    }//GEN-LAST:event_seasonsLabelMouseClicked

    private void seasonsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seasonsLabelMouseEntered
        seasonsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seasonsButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_seasonsLabelMouseEntered

    private void seasonsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seasonsLabelMouseExited
        if (mainCase != 1) {
            seasonsButton.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_seasonsLabelMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JPanel episodesButton;
    private totseries_it1b.View.Rankings.MostViewed.EpisodesByViewsRanking episodesByViewsRanking1;
    private javax.swing.JLabel episodesLabel;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel seasonsButton;
    private totseries_it1b.View.Rankings.MostViewed.SeasonsByViewsRanking seasonsByViewsRanking1;
    private javax.swing.JLabel seasonsLabel;
    private javax.swing.JPanel seriesButton;
    private totseries_it1b.View.Rankings.MostViewed.SeriesByViewsRanking seriesByViewsRanking1;
    private javax.swing.JLabel seriesLabel;
    // End of variables declaration//GEN-END:variables
}
