/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;
import java.awt.CardLayout;
/**
 *
 * @author enric
 */
public class CatalogContainer extends javax.swing.JPanel {

    /**
     * Creates new form CatalogContainer
     */
    public CatalogContainer() {
        initComponents();
    }
    
    public SerieSeasons getSeasons(){
        return serieSeasons1;
    }
    
    public void showEpisodeCard(String title,String id, int num){
        seasonEpisodes1.updateSeason(title, id, num);
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "episodes");        
    }
    
    public void showSeasonCard(String title, String id){
        serieSeasons1.updateSerie(title, id);
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "seasons");        
    }
    
    public void showCatalogCard(){
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "catalogPanel");        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catalogPanel1 = new totseries_it1b.View.CatalogPanel();
        serieSeasons1 = new totseries_it1b.View.SerieSeasons();
        seasonEpisodes1 = new totseries_it1b.View.SeasonEpisodes();

        setPreferredSize(new java.awt.Dimension(967, 614));
        setLayout(new java.awt.CardLayout());
        add(catalogPanel1, "catalogPanel");
        add(serieSeasons1, "seasons");

        javax.swing.GroupLayout seasonEpisodes1Layout = new javax.swing.GroupLayout(seasonEpisodes1);
        seasonEpisodes1.setLayout(seasonEpisodes1Layout);
        seasonEpisodes1Layout.setHorizontalGroup(
            seasonEpisodes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        seasonEpisodes1Layout.setVerticalGroup(
            seasonEpisodes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        add(seasonEpisodes1, "episodes");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private totseries_it1b.View.CatalogPanel catalogPanel1;
    private totseries_it1b.View.SeasonEpisodes seasonEpisodes1;
    private totseries_it1b.View.SerieSeasons serieSeasons1;
    // End of variables declaration//GEN-END:variables
}
