/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

/**
 *
 * @author enric
 */
public class CatalogContainer extends javax.swing.JPanel {

    /**
     * Creates new form CatalogContainer
     */
    public CatalogContainer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catalogPanel1 = new totseries_it1b.View.CatalogPanel();
        serieSeasons1 = new totseries_it1b.View.SerieSeasons();

        setPreferredSize(new java.awt.Dimension(967, 614));
        setLayout(new java.awt.CardLayout());
        add(catalogPanel1, "catalogPanel");
        add(serieSeasons1, "seasons");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private totseries_it1b.View.CatalogPanel catalogPanel1;
    private totseries_it1b.View.SerieSeasons serieSeasons1;
    // End of variables declaration//GEN-END:variables
}
