/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

import totseries_it1b.View.Catalog.CatalogPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javafx.scene.control.TabPane;
import javax.swing.JButton;
import javax.swing.JTabbedPane;
import totseries_it1b.Controller.TSController;

/**
 *
 * @author ecalvove7.alumnes
 */
public class MainScreen extends javax.swing.JFrame {

    private int mainCase = 0;

    /**
     * Creates new form totSeries
     */
    public MainScreen() {
        initComponents();
        if (TSController.getInstance().isLogged()) {
            auxButton.setText("LOG OUT");
        } else {
            auxButton.setText("LOG IN");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tittlePanel = new javax.swing.JPanel();
        totSeriesLabel = new javax.swing.JLabel();
        auxButton = new javax.swing.JButton();
        buttonsPanel = new javax.swing.JPanel();
        catalogButton = new javax.swing.JPanel();
        catalogLabel = new javax.swing.JLabel();
        mostRatedButton = new javax.swing.JPanel();
        mostRatedLabel = new javax.swing.JLabel();
        mostViewedButton = new javax.swing.JPanel();
        mostViewedLabel = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        catalogContainer1 = new totseries_it1b.View.Catalog.CatalogContainer();
        byViewsRankings = new totseries_it1b.View.Rankings.MostViewed.ByViewsRankingsPanel();
        byRatingRankings = new totseries_it1b.View.Rankings.BestRated.ByRatingRankingsPanel();
        bakcGroundIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 750));
        setPreferredSize(new java.awt.Dimension(1250, 820));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittlePanel.setBackground(new java.awt.Color(0, 0, 102));
        tittlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        totSeriesLabel.setFont(new java.awt.Font("Cooper Black", 3, 36)); // NOI18N
        totSeriesLabel.setForeground(new java.awt.Color(255, 255, 255));
        totSeriesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totSeriesLabel.setText("TotSeries.com");

        auxButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        auxButton.setText("LOG IN");
        auxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tittlePanelLayout = new javax.swing.GroupLayout(tittlePanel);
        tittlePanel.setLayout(tittlePanelLayout);
        tittlePanelLayout.setHorizontalGroup(
            tittlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tittlePanelLayout.createSequentialGroup()
                .addComponent(totSeriesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 591, Short.MAX_VALUE)
                .addComponent(auxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        tittlePanelLayout.setVerticalGroup(
            tittlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totSeriesLabel)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tittlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(auxButton)
                .addContainerGap())
        );

        getContentPane().add(tittlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, -1));

        buttonsPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        catalogButton.setBackground(Color.GRAY);

        catalogLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        catalogLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        catalogLabel.setText("Catalog");
        catalogLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catalogLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                catalogLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                catalogLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout catalogButtonLayout = new javax.swing.GroupLayout(catalogButton);
        catalogButton.setLayout(catalogButtonLayout);
        catalogButtonLayout.setHorizontalGroup(
            catalogButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catalogLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        catalogButtonLayout.setVerticalGroup(
            catalogButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catalogLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mostRatedButton.setBackground(new java.awt.Color(255, 255, 255));

        mostRatedLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mostRatedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostRatedLabel.setText("Most rated");
        mostRatedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostRatedLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostRatedLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostRatedLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mostRatedButtonLayout = new javax.swing.GroupLayout(mostRatedButton);
        mostRatedButton.setLayout(mostRatedButtonLayout);
        mostRatedButtonLayout.setHorizontalGroup(
            mostRatedButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mostRatedButtonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mostRatedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mostRatedButtonLayout.setVerticalGroup(
            mostRatedButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostRatedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mostViewedButton.setBackground(new java.awt.Color(255, 255, 255));

        mostViewedLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mostViewedLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostViewedLabel.setText("Most viewed");
        mostViewedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostViewedLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mostViewedLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mostViewedLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout mostViewedButtonLayout = new javax.swing.GroupLayout(mostViewedButton);
        mostViewedButton.setLayout(mostViewedButtonLayout);
        mostViewedButtonLayout.setHorizontalGroup(
            mostViewedButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostViewedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
        );
        mostViewedButtonLayout.setVerticalGroup(
            mostViewedButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mostViewedLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalogButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostViewedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(mostRatedButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostRatedButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(catalogButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostViewedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 960, 40));

        mainContainer.setBackground(new java.awt.Color(255, 255, 255));
        mainContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mainContainer.setOpaque(false);
        mainContainer.setLayout(new java.awt.CardLayout());
        mainContainer.add(catalogContainer1, "catalogContainer");
        mainContainer.add(byViewsRankings, "views");
        mainContainer.add(byRatingRankings, "ratings");

        getContentPane().add(mainContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 960, 610));

        bakcGroundIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fonsMainMenu.png"))); // NOI18N
        getContentPane().add(bakcGroundIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catalogLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogLabelMouseClicked
        mainCase = 0;
        catalogButton.setBackground(Color.GRAY);
        mostViewedButton.setBackground(Color.WHITE);
        mostRatedButton.setBackground(Color.WHITE);
        CardLayout card = (CardLayout) mainContainer.getLayout();
        card.show(mainContainer, "catalogContainer");
        catalogContainer1.showCatalogCard();
    }//GEN-LAST:event_catalogLabelMouseClicked

    private void mostViewedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostViewedLabelMouseClicked
        mainCase = 1;
        catalogButton.setBackground(Color.WHITE);
        mostViewedButton.setBackground(Color.GRAY);
        mostRatedButton.setBackground(Color.WHITE);
        CardLayout card = (CardLayout) mainContainer.getLayout();
        card.show(mainContainer, "views");
    }//GEN-LAST:event_mostViewedLabelMouseClicked

    private void mostRatedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostRatedLabelMouseClicked
        mainCase = 2;
        catalogButton.setBackground(Color.WHITE);
        mostViewedButton.setBackground(Color.WHITE);
        mostRatedButton.setBackground(Color.GRAY);
        CardLayout card = (CardLayout) mainContainer.getLayout();
        card.show(mainContainer, "ratings");
    }//GEN-LAST:event_mostRatedLabelMouseClicked

    private void mostRatedLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostRatedLabelMouseEntered
        mostRatedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostRatedButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_mostRatedLabelMouseEntered

    private void mostViewedLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostViewedLabelMouseEntered
        mostViewedButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostViewedButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_mostViewedLabelMouseEntered

    private void catalogLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogLabelMouseEntered
        catalogButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catalogButton.setBackground(Color.GRAY);
    }//GEN-LAST:event_catalogLabelMouseEntered

    private void catalogLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalogLabelMouseExited
        if (mainCase != 0) {
            catalogButton.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_catalogLabelMouseExited

    private void mostViewedLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostViewedLabelMouseExited
        if (mainCase != 1) {
            mostViewedButton.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_mostViewedLabelMouseExited

    private void mostRatedLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostRatedLabelMouseExited
        if (mainCase != 2) {
            mostRatedButton.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_mostRatedLabelMouseExited

    private void auxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxButtonActionPerformed
        TSController ctrl = TSController.getInstance();
        if (ctrl.isLogged()) {
            ctrl.logout();
        }
        this.dispose();
        InitialScreen initial = new InitialScreen();
        initial.setVisible(true);
    }//GEN-LAST:event_auxButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton auxButton;
    private javax.swing.JLabel bakcGroundIcon;
    private javax.swing.JPanel buttonsPanel;
    private totseries_it1b.View.Rankings.BestRated.ByRatingRankingsPanel byRatingRankings;
    private totseries_it1b.View.Rankings.MostViewed.ByViewsRankingsPanel byViewsRankings;
    private javax.swing.JPanel catalogButton;
    private totseries_it1b.View.Catalog.CatalogContainer catalogContainer1;
    private javax.swing.JLabel catalogLabel;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPanel mostRatedButton;
    private javax.swing.JLabel mostRatedLabel;
    private javax.swing.JPanel mostViewedButton;
    private javax.swing.JLabel mostViewedLabel;
    private javax.swing.JPanel tittlePanel;
    private javax.swing.JLabel totSeriesLabel;
    // End of variables declaration//GEN-END:variables
    private CatalogPanel catalogPanel;
    private JTabbedPane rankingsTabsPanel;
}
