/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

import javafx.scene.control.TabPane;
import javax.swing.JButton;
import javax.swing.JTabbedPane;

/**
 *
 * @author ecalvove7.alumnes
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form totSeries
     */
    public MainScreen() {
        initComponents();
        initMainComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(mainContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initMainComponents() {
        catalogPanel = new CatalogPanel();
        rankingsTabsPanel = new JTabbedPane();
        seriesRankings = new SeriesRanking();

        mainContainer.add(catalogPanel);
        mainContainer.add(rankingsTabsPanel);

        rankingsTabsPanel.addTab("Series", seriesRankings);
        rankingsTabsPanel.setBounds(0, 0, 500, 500);

        pack();
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainContainer;
    // End of variables declaration//GEN-END:variables
    private CatalogPanel catalogPanel;
    private JTabbedPane rankingsTabsPanel;
    private SeriesRanking seriesRankings;
}
