/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

/**
 *
 * @author ecalvove7.alumnes
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTitle = new javax.swing.JLabel();
        registerPanel = new javax.swing.JPanel();
        registerBorder = new javax.swing.JPanel();
        registerBackGround = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        logginBorder = new javax.swing.JPanel();
        registerBackGround1 = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainTitle.png"))); // NOI18N
        getContentPane().add(mainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1910, 100));

        registerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerBorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        registerBorder.setOpaque(false);

        javax.swing.GroupLayout registerBorderLayout = new javax.swing.GroupLayout(registerBorder);
        registerBorder.setLayout(registerBorderLayout);
        registerBorderLayout.setHorizontalGroup(
            registerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        registerBorderLayout.setVerticalGroup(
            registerBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        registerPanel.add(registerBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        registerBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fonsMainMenu2.png"))); // NOI18N
        registerPanel.add(registerBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -50, 700, 420));

        getContentPane().add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 600, 340));

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logginBorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 7));
        logginBorder.setOpaque(false);

        javax.swing.GroupLayout logginBorderLayout = new javax.swing.GroupLayout(logginBorder);
        logginBorder.setLayout(logginBorderLayout);
        logginBorderLayout.setHorizontalGroup(
            logginBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        logginBorderLayout.setVerticalGroup(
            logginBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        loginPanel.add(logginBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        registerBackGround1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fonsMainMenu2.png"))); // NOI18N
        loginPanel.add(registerBackGround1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -60, 820, 500));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 600, 340));

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fonsMainMenu.png"))); // NOI18N
        getContentPane().add(backGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1910, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JPanel logginBorder;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JLabel registerBackGround;
    private javax.swing.JLabel registerBackGround1;
    private javax.swing.JPanel registerBorder;
    private javax.swing.JPanel registerPanel;
    // End of variables declaration//GEN-END:variables
}
