/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

import java.awt.CardLayout;
import totseries_it1b.Controller.TSController;

/**
 *
 * @author enric
 */
public abstract class ParentPanel extends javax.swing.JPanel {
    String id;
    String title;
    int numEpisode;
    int numSeason;
    TSController ctrl;
    boolean readOnly;
    /**
     * Creates new form ParentPanel
     */
    public ParentPanel(String title, String id) {
        initComponents();
        initComponents();
        this.title = title;
        titleLabel.setText(title);
        this.id = id;
        ctrl = TSController.getInstance();
        readOnly = false;
        numEpisode = 0;
        numSeason = 0;
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
    }
    
    public ParentPanel(String title, String id, boolean read) {
        initComponents();
        initComponents();
        titleLabel.setText(title);
        this.id = id;
        ctrl = TSController.getInstance();
        readOnly = read;
        numEpisode = 0;
        numSeason = 0;
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
    }
    
    public ParentPanel(String title, String id, boolean read, int num) {
        initComponents();
        initComponents();
        titleLabel.setText(title);
        this.id = id;
        ctrl = TSController.getInstance();
        readOnly = read;
        numEpisode = num;
        numSeason = num;
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
    }
     
    protected abstract void formMouseEntered(java.awt.event.MouseEvent evt);
    protected abstract void formMouseExited(java.awt.event.MouseEvent evt);
    protected abstract void formMouseClicked(java.awt.event.MouseEvent evt);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        infoPanelContainer = new javax.swing.JPanel();
        infoEpisode = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        titlePanel.setBackground(new java.awt.Color(51, 51, 51));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("jLabel1");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        add(titlePanel, java.awt.BorderLayout.CENTER);

        infoPanelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoEpisode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoPanelContainer.add(infoEpisode, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 155, 212));

        add(infoPanelContainer, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
   /* */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoEpisode;
    public javax.swing.JPanel infoPanelContainer;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
