/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import totseries_it1b.Model.Ranking;

/**
 *
 * @author Enric Calvo & German Barquero
 */
public abstract class RankingPanel extends javax.swing.JPanel implements Observer {

    /**
     * Creates new form RankingPanel
     */
    public RankingPanel(Ranking ranking) {
        initComponents();
        model = new DefaultListModel();
        rankingList.setModel(model);
        ranking.addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rankingList = new javax.swing.JList();

        jScrollPane1.setViewportView(rankingList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList rankingList;
    // End of variables declaration//GEN-END:variables
    protected DefaultListModel model;

    @Override
    public abstract void update(Observable o, Object arg);

    protected abstract void load(Ranking ranking);

    protected abstract void addElementToRanking(Object obj);

    protected void clearRanking() {
        model.clear();
    }
}
