/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

import java.util.ArrayList;
import totseries_it1b.Controller.TSController;

/**
 *
 * @author enric
 */
public class SeasonEpisodes extends javax.swing.JPanel {

    /**
     * Creates new form seasonEpisodes
     */
    
    ArrayList<EpisodePanel> episodesPanels;
    TSController ctrl;
    
    public SeasonEpisodes() {
        initComponents();
        ctrl = TSController.getInstance();
    }
    
    public void updateSeason(String title, String id, int num){
        mainSeriePanel.removeAll();
        mainSeriePanel.add(new SeriePanel(title, id, true));
        episodesPanels = new ArrayList<EpisodePanel>();
        for (String[] episode : ctrl.getInfoEpisodes(id, num)) {
            EpisodePanel panel = new EpisodePanel(episode[0], episode[1], true, num);
            episodesPanels.add(panel);
        }updateEpisode(episodesPanels);
    }
    public void updateEpisode(ArrayList<EpisodePanel> episodesPanels){
        episodesPanel.removeAll();
        for(EpisodePanel panel:episodesPanels){
            episodesPanel.add(panel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSeriePanel = new javax.swing.JPanel();
        episodesPanel = new javax.swing.JPanel();
        numberSeasonLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(960, 637));

        mainSeriePanel.setBackground(new java.awt.Color(255, 255, 255));
        mainSeriePanel.setPreferredSize(new java.awt.Dimension(160, 240));

        episodesPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout episodesPanelLayout = new javax.swing.GroupLayout(episodesPanel);
        episodesPanel.setLayout(episodesPanelLayout);
        episodesPanelLayout.setHorizontalGroup(
            episodesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 913, Short.MAX_VALUE)
        );
        episodesPanelLayout.setVerticalGroup(
            episodesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );

        numberSeasonLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberSeasonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numberSeasonLabel.setText("SEASON NUMBER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(episodesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainSeriePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(numberSeasonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainSeriePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberSeasonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(episodesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel episodesPanel;
    private javax.swing.JPanel mainSeriePanel;
    private javax.swing.JLabel numberSeasonLabel;
    // End of variables declaration//GEN-END:variables
}
