/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

import javax.swing.JLabel;

/**
 *
 * @author ecalvove7.alumnes
 */
public class SeriePanel extends javax.swing.JPanel {

    String id;

    /**
     * Creates new form SeriePanel
     */
    public SeriePanel(String title, String id) {
        initComponents();
        titleSerie.setText(title);
        this.id = id;

    }

    public void prova(String toAdd) {
        JLabel label = new JLabel(toAdd);
        jPanel2.add(label);
        label.show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleSerie = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(157, 234));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        titleSerie.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        titleSerie.setForeground(new java.awt.Color(255, 255, 255));
        titleSerie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSerie.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 204, -1, -1));
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 190));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel titleSerie;
    // End of variables declaration//GEN-END:variables
}
