/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View;

import java.util.ArrayList;
import totseries_it1b.Controller.TSController;

/**
 *
 * @author enric
 */
public class SerieSeasons extends javax.swing.JPanel {
    ArrayList<SeasonPanel> seasonsPanels;
    TSController ctrl;
    /*
     * Creates new form SerieSeasons
     */
    public SerieSeasons(){
        initComponents();
        ctrl = TSController.getInstance();
    }
    
    public void updateSerie(String title, String id){
        mainSeriePanel.removeAll();
        mainSeriePanel.add(new SeriePanel(title, id, true));
        seasonsPanels = new ArrayList<SeasonPanel>();
        for (String[] season : ctrl.getInfoSeasons(id)) {
            SeasonPanel panel = new SeasonPanel("SEASON "+season[0], season[1],false, Integer.parseInt(season[0]));
            seasonsPanels.add(panel);
        }updateSeason(seasonsPanels);
    }
    public void updateSeason(ArrayList<SeasonPanel> seasonsPanels){
        seasonsPanel.removeAll();
        for(SeasonPanel panel:seasonsPanels){
            seasonsPanel.add(panel);
        }
    }
    /*public SerieSeasons(String title, String id) {
        initComponents();
        SeriePanel seriePanel = new SeriePanel(title,id);
        mainSeriePanel.add(seriePanel);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSeriePanel = new javax.swing.JPanel();
        seasonsPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        mainSeriePanel.setBackground(new java.awt.Color(255, 255, 255));
        mainSeriePanel.setPreferredSize(new java.awt.Dimension(160, 240));

        seasonsPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seasonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainSeriePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(mainSeriePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seasonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainSeriePanel;
    private javax.swing.JPanel seasonsPanel;
    // End of variables declaration//GEN-END:variables
}
