/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View.Catalog;
import java.awt.CardLayout;
/**
 *
 * @author enric
 */
public class CatalogContainer extends javax.swing.JPanel {

    /**
     * Creates new form CatalogContainer
     */
    public CatalogContainer() {
        initComponents();
    }
    
    /*public SerieSeasons getSeasons(){
        return serieSeasons1;
    }*/
    
    public void showEpisodeCard(String title,String id, int num){
        CardLayout card1 = (CardLayout)this.getLayout();
        card1.show(this, "seasonsAndEpisodes");  
        seasonsAndEpisodes1.updateSeason(title, id, num);                
    }
    
    public void showWatchCard(String title,String id, int num,String inforEpisode, String description, int season){
        CardLayout card1 = (CardLayout)this.getLayout();
        card1.show(this, "seasonsAndEpisodes");  
        seasonsAndEpisodes1.updateEpisode(title, id, num, inforEpisode, description, season);                
    }
    
    public void showSeasonCard(String title, String id){
        CardLayout card1 = (CardLayout)this.getLayout();
        card1.show(this, "seasonsAndEpisodes");        
        seasonsAndEpisodes1.updateSerie(title, id);
    }
    
    public void showCatalogCard(){
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "catalogPanel");        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catalogPanel1 = new totseries_it1b.View.Catalog.CatalogPanel();
        seasonsAndEpisodes1 = new totseries_it1b.View.Catalog.SeasonsAndEpisodes();

        setPreferredSize(new java.awt.Dimension(967, 614));
        setLayout(new java.awt.CardLayout());
        add(catalogPanel1, "catalogPanel");
        add(seasonsAndEpisodes1, "seasonsAndEpisodes");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private totseries_it1b.View.Catalog.CatalogPanel catalogPanel1;
    private totseries_it1b.View.Catalog.SeasonsAndEpisodes seasonsAndEpisodes1;
    // End of variables declaration//GEN-END:variables
}
