/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totseries_it1b.View.Catalog;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import totseries_it1b.View.BasicPanels.EpisodePanel;

/**
 *
 * @author enric
 */
public class WatchEpisode extends javax.swing.JPanel {

    /**
     * Creates new form WatchEpisode
     */
    public WatchEpisode() {
        initComponents();
        timer = new Timer(50, new progress());
    }
    
    public void updateEpisode(EpisodePanel episodePanel, String description){
        episode.removeAll();
        episode.add(episodePanel);
        episodeDescription.setText(description);
        progress.setValue(0);
        panelStars1.setVisible(false);
        rateEpisodeLabel.setVisible(false);
    }

    public class progress implements ActionListener {

        public void actionPerformed(ActionEvent evt) {
            int n = progress.getValue();
            if (n < 100) {
                n++;
                progress.setValue(n);
            } else {
                timer.stop();
                // AQUI CREAR VIEW I ENLLAÇAR AMB RATE??
                JOptionPane.showMessageDialog(null, "episode watched");
                panelStars1.setVisible(true);
                rateEpisodeLabel.setVisible(true);
            }
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        episode = new javax.swing.JPanel();
        episodeDescription = new javax.swing.JTextPane();
        watchEpisode = new javax.swing.JButton();
        progress = new javax.swing.JProgressBar();
        panelStars1 = new totseries_it1b.View.BasicPanels.panelStars();
        rateEpisodeLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(913, 324));

        episode.setBackground(new java.awt.Color(255, 255, 255));

        watchEpisode.setText("WATCH");
        watchEpisode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                watchEpisodeActionPerformed(evt);
            }
        });

        progress.setMinimumSize(new java.awt.Dimension(146, 17));
        progress.setStringPainted(true);

        rateEpisodeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rateEpisodeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rateEpisodeLabel.setText("RATE EPISODE:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(episode, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(panelStars1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))
                            .addComponent(episodeDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(watchEpisode, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(rateEpisodeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13)))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(episodeDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rateEpisodeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelStars1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(watchEpisode, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(episode, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void watchEpisodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_watchEpisodeActionPerformed
        timer.start();
    }//GEN-LAST:event_watchEpisodeActionPerformed

    private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel episode;
    private javax.swing.JTextPane episodeDescription;
    private totseries_it1b.View.BasicPanels.panelStars panelStars1;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel rateEpisodeLabel;
    private javax.swing.JButton watchEpisode;
    // End of variables declaration//GEN-END:variables
}
